### ISSUE TITLE
Include server side encryption in dynamo db creation

### ISSUE THREAD

**Issue by Aravind04101996** [nozaq/terraform-aws-remote-state-s3-backend#69] opened 2022-03-07 22:00 UTC
As a best practice, please enable server side encryption in dynamo db table creation 

dynamo.tf

server_side_encryption {
    enabled     = var.server_side_encryption_enabled
    kms_key_arn = var.server_side_encryption_kms_key_arn
  }

**Comment by Aravind36064** [comment] 2022-03-08 03:45
Duplicate of #70

**Closed** 2022-03-08 12:40 UTC
